main-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'users/:id/request_code'   => 'users/sms_verifications#request_code',   as: 'request_code'
    post 'users/:id/verify_account' => 'users/sms_verifications#verify_account', as: 'verify_account'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'
  mount ElectionObservation::Api, at: '/'

  root  to: 'home#index'
  get 'filter_stations' => 'home#filter_stations'

  resources :closing_protocols do
    get :candidates, on: :collection
  end

  resources :stations, only: %i[index show]

  namespace :results do
    resources :elections, only: %i[index show], controller: 'elections' do
      resources :districts, only: %i[index show], controller: 'elections/districts' do
        get :local_areas, on: :member

        resources :stations, controller: 'elections/stations'
      end
    end
  end

  scope module: 'users' do
    resource :profile
    resources :observers_stations, only: %i[create update destroy] do
      delete :delete_certificate, on: :member
    end
  end

  namespace :admins do
    root 'dashboard#index'

    resources :election_groups do
      patch :publish, on: :member

      resources :public_organizations, only: %i[index update], controller: 'election_groups/public_organizations'
    end
    resources :public_organizations do
      resources :users, controller: 'public_organizations/users'
    end
    resources :elections, only: %i[index create update destroy show] do
      resources :candidates, controller: 'elections/candidates'
      resources :electoral_districts, only: %i[index destroy], controller: 'elections/electoral_districts'
      resources :stations, only: %i[index update destroy], controller: 'elections/stations' do
        get :filtered, on: :collection
      end
    end
    resources :local_areas, only: :update
  end

  namespace :cabinet do
    root 'dashboard#index'

    devise_scope :user do
      get 'sign_in' => 'sessions#new'
    end

    resources :closing_protocols do
      collection do
        get :filter
        get :search
        get :reset_filter
        patch :batch_delete
      end
      member do
        patch :approve
        patch :reject
        patch :delete
        patch :batch_reject
      end
    end
    resources :users
    resources :election_groups do
      resources :observers_stations, only: %i[index show], controller: 'election_groups/observers_stations' do
        member do
          patch :approve
          patch :reject
        end
      end
    end
  end

  namespace :api do
    namespace :v1, default: { format: :json } do
      resources :regions
      resources :local_areas
      resources :stations
      resources :elections
      resources :candidates

      namespace :mobile do
        post 'user_token' => 'user_token#create'
        get 'token_login' => 'users#me'
      end
    end
  end
end

main-app/app/models/election.rb
class Election < ApplicationRecord
  enum status: %i[draft ready]

  belongs_to :election_group

  has_and_belongs_to_many :electoral_districts
  has_and_belongs_to_many :stations

  has_many :candidates, dependent: :destroy
  has_many :closing_protocols, dependent: :destroy

  validates :name, :date, presence: true

  def pinned!
    self.update!(pinned: true)
  end

  def candidates_exist?
    candidates.size > 0
  end

  def district_by_station(station)
    self.electoral_districts.find do |district|
      if district.level == 1
        true
      elsif district.level == 2
        district.scopeable.local_areas.flat_map(&:stations).include?(station)
      elsif district.level == 3
        district.scopeable.stations.include?(station)
      end
    end
  end
end

main-app/app/models/station.rb
class Station < ApplicationRecord
  include ActiveModel::Serialization
  include StationsFilterable

  COORDINATES_FORMAT = /\A\d+\.\d+\,\ *\d+\.\d+\z/.freeze

  belongs_to :election_group
  belongs_to :local_area

  has_many :closing_protocols, dependent: :destroy
  has_many :observers_stations, dependent: :destroy
  has_many :observers, through: :observers_stations, source: :user

  has_and_belongs_to_many :elections

  validates :name, presence: true, uniqueness: {scope: :local_area_id}

  before_save :check_coordinates

  delegate_missing_to :local_area

  class << self
    def parent_levels(election_group_id)
      query = <<-SQL
      SELECT
        c.id AS country_id, c.name AS country_name,
        r.id AS region_id, r.name AS region_name,
        l.id AS local_area_id, l.name AS local_area_name
      FROM countries c
      LEFT JOIN regions r ON r.country_id = c.id
      LEFT JOIN local_areas l ON l.region_id = r.id
      LEFT JOIN stations s ON s.local_area_id = l.id
      WHERE s.election_group_id = ?
      GROUP BY c.id, c.name, r.id, r.name, l.id, l.name
      ORDER BY c.name, r.name, l.name;
      SQL

      self.connection.execute(
        sanitize_sql([query, election_group_id])
      ).to_a
    end
  end

  def full_address
    "#{region.name}, #{local_area.name}, #{address}"
  end

  private

  def check_coordinates
    return if self.coordinates.nil?
    return if self.coordinates.match?(COORDINATES_FORMAT)

    self.coordinates = nil
  end
end

main-app/app/controllers/admins/elections/candidates_controller.rb
class Admins::Elections::CandidatesController < Admins::ApplicationController
  before_action :set_election, only: %i[index new create edit update destroy]
  before_action :set_candidate, only: %i[edit update destroy]

  def index
    respond_with(@candidates = @election.candidates.includes(electoral_district: [:scopeable]))
  end

  def new
    respond_with(@candidate = @election.candidates.new)
  end

  def create
    respond_with(@candidate = Candidate.create(candidate_params), location: admins_election_candidates_path(@election))
  end

  def edit
  end

  def update
    @candidate.update(candidate_params)
    respond_with(@candidate, location: admins_election_candidates_path(@election))
  end

  def destroy
    @candidate.destroy
    respond_with(@candidate, location: admins_election_candidates_path(@election))
  end

  private

  def candidate_params
    params.require(:candidate).permit(:name, :info, :election_id)
  end

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

  def set_election
    @election = Election.find(params[:election_id])
  end
end

main-app/app/controllers/admins/elections/electoral_districts_controller.rb
class Admins::Elections::ElectoralDistrictsController < Admins::ApplicationController
  before_action :set_election, only: %i[index destroy]
  before_action :set_local_area, :set_district, only: :destroy

  def index
    @district_local_areas = LocalArea.by_election(@election).order(:region_id)
  end

  def destroy
    @election.electoral_districts.delete(@district)
    redirect_to admins_election_electoral_districts_path(@election)
  end

  private

  def set_election
    @election = Election.find(params[:election_id])
  end

  def set_local_area
    @local_area = LocalArea.find(params[:local_area_id])
  end

  def set_district
    @district =
      @local_area.electoral_district ||
      @local_area.region.electoral_district ||
      @local_area.country.electoral_district
  end
end

main-app/app/controllers/admins/elections/stations_controller.rb
class Admins::Elections::StationsController < Admins::ApplicationController
  before_action :set_election
  before_action :set_local_area, only: :filtered

  respond_to :js

  def index
    @districts = Station.parent_levels(@election.election_group_id)
  end

  def filtered
    @stations = @local_area.stations.where(election_group_id: @election.election_group_id).sort_by(&:name)

    render json: @stations.to_json
  end

  private

  def set_election
    @election = Election.find(params[:election_id])
  end

  def set_local_area
    @local_area = LocalArea.find(params[:local_area_id])
  end
end

main-app/app/controllers/admins/elections_controller.rb
class Admins::ElectionsController < Admins::ApplicationController
  before_action :set_election, only: %i[update show destroy]
  before_action :set_election_group, only: %i[create update destroy]
  before_action :set_election_groups, only: :index

  after_action :update_group_status, only: :destroy

  respond_to :js

  def index
    @elections = Election.includes(:election_group, :stations).order(:date)
  end

  def show
  end

  def create
    result = Election::Create.call(
      election_params: election_params,
      districts:       params[:election][:districts],
      candidates:      params[:election][:candidates]
    )

    if result.success?
      flash[:notice] = I18n.t('messages.actions.create.success')
    else
      flash[:error] = result.message
    end

    redirect_to admins_elections_path
  end

  def update
    result = Election::Update.call(
      election: @election,
      election_group: @election.election_group,
      election_params: election_params,
      districts:       params[:election][:districts],
      candidates:      params[:election][:candidates]
    )

    if result.success?
      flash[:notice] = I18n.t('messages.actions.update.success')
    else
      flash[:error] = result.message
    end

    redirect_to admins_elections_path
  end

  def destroy
    respond_with(@election.destroy, location: admins_elections_path)
  end

  private

  def election_params
    params.require(:election).permit(:name, :date, :pinned, :election_group_id)
  end

  def set_election
    @election = Election.find(params[:id])
  end

  def set_election_group
    id = params[:election].present? ? election_params[:election_group_id] : nil
    @election_group = id ? ElectionGroup.find(id) : @election.election_group
  end

  def set_election_groups
    gon.election_groups = ElectionGroup.all.collect { |eg| [eg.id, eg.date&.strftime('%Y-%m-%d')] }.to_h
  end

  def update_group_status
    ::ElectionGroups::UpdateStatus.call(election_group: @election_group)
  end
end

main-app/app/controllers/api/v1/elections_controller.rb
class Api::V1::ElectionsController < Api::V1::BaseController
  before_action :set_election

  def show
    render json: @election, serializer: ElectionSerializer, each_serializer: CandidateSerializer
  end

  private

  def set_election
    @election = Election.find_by(id: params[:id])
  end
end

main-app/app/controllers/api/v1/stations_controller.rb
class Api::V1::StationsController < Api::V1::BaseController
  before_action :set_local_area

  def show
    render json: @local_area.stations, each_serializer: StationSerializer
  end

  private

  def set_local_area
    @local_area = LocalArea.find_by(id: params[:id])
  end
end

main-app/app/controllers/results/elections/districts_controller.rb
class Results::Elections::DistrictsController < ApplicationController
  include ResultsDownloaded

  before_action :set_election, :set_district, only: %i[show local_areas]
  before_action :set_region, only: :local_areas

  respond_to :js

  def show
    result = Results::Districts::New.call(
      region_id: params[:region_id],
      local_area_id: params[:local_area_id],
      page: params[:page],
      district: @district,
      election: @election
    )

    @general_details = result.general_details
    @results = result.district_results
    gon.correct_protocols_stations = result.red_stations
    gon.non_correct_protocols_stations = result.gray_stations

    base_responders_with_xlsx("Результаты_выборов_#{@election.id}-#{@district.id}")
  end

  def local_areas
    local_areas = @region.local_areas.includes(stations: :closing_protocols)
                    .where(stations: { closing_protocols: { status: 'correct' }})

    render json: local_areas.to_json
  end

  private

  def set_district
    @district = ElectoralDistrict.find(params[:id])
  end

  def set_election
    @election = Election.find(params[:election_id])
  end

  def set_region
    @region = Region.find(params[:region_id])
  end
end

main-app/app/controllers/results/elections/stations_controller.rb
class Results::Elections::StationsController < ApplicationController
  include ResultsDownloaded

  before_action :set_station,
                :set_election,
                :set_district,
                :set_candidates, only: :show

  def show
    @station_closing_protocols = @station.closing_protocols
      .includes(candidates_closing_protocols: :candidate)
      .joins(:election)
      .where(election: @election).order(status: :desc)

    base_responders_with_xlsx("Результаты_выборов_#{@election.id}_#{@district.id}_#{@station.id}")
  end

  private

  def set_station
    @station = election_group.stations.find_by(id: params[:id])
  end

  def set_election
    @election = Election.find(params[:election_id])
  end

  def set_district
    @district = ElectoralDistrict.find(params[:district_id])
  end

  def set_candidates
    @candidates = @district.candidates.where(election_id: @election.id)
  end
end

main-app/app/controllers/results/elections_controller.rb
class Results::ElectionsController < ApplicationController
  include ResultsDownloaded

  before_action :set_election, only: %i[show local_areas]

  def index
    @elections = election_group.elections

    base_responders_with_xlsx("Результаты_выборов")
  end

  def show
    @electoral_districts = @election.electoral_districts.includes(:scopeable)

    redirect_to results_election_district_path(@electoral_districts.first) if @electoral_districts.size == 1

    base_responders_with_xlsx("Результаты_выборов_#{@election.id}")
  end

  private

  def set_election
    @election = Election.find(params[:id])
  end
end

main-app/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_public_orgs, only: %i[index show]
  before_action :set_regions,
                :set_local_areas,
                :set_stations, only: %i[index]
  before_action :set_station,  only: :show

  respond_to :js

  def index
    if params[:station].present?
      @stations_info = ::Stations::Filter.call(
        election_group: election_group,
        public_organization_ids: station_params[:public_organization_ids],
        public_organization_type: station_params[:public_organization_type],
        observer_type: station_params[:observer_type],
        region_id: station_params[:region_id],
        local_area_id: station_params[:local_area_id],
        station_ids: station_params[:station_ids],
        observer_id: current_user.id
      ).stations_info
    end

    respond_to do |format|
      format.html
      format.json { render json: @stations_info.to_json }
    end
  end

  def show
    @observers_station = current_user.observers_stations.find_by(station: @station) || @station.observers_stations.new
  end

  private

  def station_params
    params.require(:station).permit(
      :region_id,
      :local_area_id,
      :public_organization_type,
      :observer_type,
      public_organization_ids: [],
      station_ids: []
    )
  end

  def set_public_orgs
    @orgs = PublicOrganization.order(:name)
  end

  def set_station
    @station = Station.find(params[:id])
  end

  def set_regions
    @regions = Region.eager_load(local_areas: [:stations]).order(:name)
  end

  def set_local_areas
    @local_areas = @regions.first.local_areas.order(:name)
  end

  def set_stations
    @stations = @local_areas.first.stations.order(:name)
  end
end

main-app/app/views/results/elections/stations/show.html.slim
= render 'shared/back_link'

.row.d-flex.justify-content-center
  .col-sm-6.p-2
    .col-wrapper
      p.col-title = @station.name
      p.col-text = @election.name
      p.col-text.color-light-gray = "#{@station.country.name} - #{@station.region.name} - #{@station.local_area.name}"

      .row.mv-16
        .col-sm-12.p-0
          .download-results-link.mb-2
            = link_to t('pages.buttons.download_results'), results_election_district_station_path(@election, @district, @station, format: :xlsx)

          .stations-elections-results
            - protocol = @station_closing_protocols.correct.first
            - if protocol.present?
              .election-results[style="margin-bottom: 10px;"]
                table.table
                  tbody
                    tr
                      td Избирателей всего
                      td.text-right
                        strong = protocol.total_voters
                    tr
                      td Явка избирателей, %
                      td.text-right
                        strong = "#{(100 * protocol.active_voters.to_f/protocol.total_voters).round(2)} %"
                    tr
                      td Избирателей проголосовавших
                      td.text-right
                        strong = protocol.active_voters
                    tr
                      td = t('activerecord.attributes.closing_protocol.invalid_bulletins')
                      td.text-right
                        strong = protocol.invalid_bulletins

                .election-candidates
                  table.table
                    thead
                      tr
                        th Кандидат
                        th Голоса
                        th.text-right %
                    tbody
                      - protocol.candidates_closing_protocols.each do |cc|
                        tr
                          td = cc.candidate.name
                          td
                            strong = cc.votes
                          td.text-right
                            strong = cc.votes.zero? ? cc.votes.to_f : (100 * cc.votes.to_f / (protocol.active_voters - protocol.invalid_bulletins)).round(2)
                a.link-to-protocol.custom-link[href="#protocol-info-#{protocol.id}"] = t('pages.stations.results.index.show_protocol')
            - else
              .election-info[style="margin-bottom: 10px;"]
                .election-name = @election.name
                .election-candidates
                  - @candidates.each do |candidate|
                    .candidate-name = candidate.name
                    .votes-count = 0
      .row.mv-16
        .col-sm-12.p-0
          p.col-title = t('pages.stations.results.index.protocols_list')
          .stations-protocols
            - @station_closing_protocols.each do |protocol|
              .station-protocol-card[id="protocol-info-#{protocol.id}" style="padding: 10px; border: 1px solid #EEEEEE; margin-bottom: 10px;"]
                .protocol-info[style="display: flex; justify-content: space-between;"]
                  .protocol = t('pages.stations.results.index.protocol')
                  .protocol-id = protocol.id
                .protocol-status[style="display: flex; justify-content: space-between;"]
                  .status-header = t('activerecord.attributes.closing_protocol.status')
                  .status-value = t("activerecord.attributes.closing_protocol.statuses.#{protocol.status}")
                .protocol-votes-info.mv-12
                  .votes-info-header = t('pages.stations.results.index.votes_count')
                  .votes-by-candidates
                    - protocol.candidates_closing_protocols.each do |candidate_protocol|
                      .candidate-votes[style="display: flex; justify-content: space-between;"]
                        .candidate-name = candidate_protocol.candidate.name
                        .votes-count
                          strong= candidate_protocol.votes
                .protocol-images
                  a.show-protocol-images.custom-link[href='#' data-id="#{protocol.id}"]
                    = t('pages.stations.results.index.show_images')
                    i.fa.fa-arrow-down.ml-2.color-green
                  .protocol-images.display-none[id="protocol-images-#{protocol.id}"]
                    .carousel.slide[data-ride="carousel" id="protocol-images-carousel-#{protocol.id}"]
                      ol.carousel-indicators
                        - protocol.images.count.times do |n|
                          li[data-target="#protocol-images-carousel-#{protocol.id}" data-slide-to="#{n}" class="#{'active' if n.zero?}"]
                      .carousel-inner
                        - protocol.images.each_with_index do |image, index|
                          .carousel-item[class="#{'active' if index.zero?}"]
                            = link_to image.url do
                              = image_tag(image.url, width: '100%', height: '500', class: 'd-block w-100')
                      a.carousel-control-prev[href="#protocol-images-carousel-#{protocol.id}" role="button" data-slide="prev"]
                        span.carousel-control-prev-icon[aria-hidden="true"]
                        span.sr-only
                      a.carousel-control-next[href="#protocol-images-carousel-#{protocol.id}" role="button" data-slide="next"]
                        span.carousel-control-next-icon[aria-hidden="true"]
                        span.sr-only