main-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'users/:id/request_code'   => 'users/sms_verifications#request_code',   as: 'request_code'
    post 'users/:id/verify_account' => 'users/sms_verifications#verify_account', as: 'verify_account'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'
  mount ElectionObservation::Api, at: '/'

  root  to: 'home#index'
  get 'filter_stations' => 'home#filter_stations'

  resources :closing_protocols do
    get :candidates, on: :collection
  end

  resources :stations, only: %i[index show]

  namespace :results do
    resources :elections, only: %i[index show], controller: 'elections' do
      resources :districts, only: %i[index show], controller: 'elections/districts' do
        get :local_areas, on: :member

        resources :stations, controller: 'elections/stations'
      end
    end
  end

  scope module: 'users' do
    resource :profile
    resources :observers_stations, only: %i[create update destroy] do
      delete :delete_certificate, on: :member
    end
  end

  namespace :admins do
    root 'dashboard#index'

    resources :election_groups do
      patch :publish, on: :member

      resources :public_organizations, only: %i[index update], controller: 'election_groups/public_organizations'
    end
    resources :public_organizations do
      resources :users, controller: 'public_organizations/users'
    end
    resources :elections, only: %i[index create update destroy show] do
      resources :candidates, controller: 'elections/candidates'
      resources :electoral_districts, only: %i[index destroy], controller: 'elections/electoral_districts'
      resources :stations, only: %i[index update destroy], controller: 'elections/stations' do
        get :filtered, on: :collection
      end
    end
    resources :local_areas, only: :update
  end

  namespace :cabinet do
    root 'dashboard#index'

    devise_scope :user do
      get 'sign_in' => 'sessions#new'
    end

    resources :closing_protocols do
      collection do
        get :filter
        get :search
        get :reset_filter
        patch :batch_delete
      end
      member do
        patch :approve
        patch :reject
        patch :delete
        patch :batch_reject
      end
    end
    resources :users
    resources :election_groups do
      resources :observers_stations, only: %i[index show], controller: 'election_groups/observers_stations' do
        member do
          patch :approve
          patch :reject
        end
      end
    end
  end

  namespace :api do
    namespace :v1, default: { format: :json } do
      resources :regions
      resources :local_areas
      resources :stations
      resources :elections
      resources :candidates

      namespace :mobile do
        post 'user_token' => 'user_token#create'
        get 'token_login' => 'users#me'
      end
    end
  end
end

main-app/app/views/shared/_back_link.html.slim
.row.d-flex.justify-content-center.hp-10
  .col-sm-6.no-padding
    .col-wrapper
      = link_to request.referer, class: 'back-link' do
        i.fa.fa-arrow-left.mr-2
        | Назад
      hr.mb-0

main-app/app/views/shared/_elections_link.html.slim
.row.d-flex.justify-content-center.hp-10
  .col-sm-6.no-padding
    .col-wrapper
      = link_to results_elections_path, class: 'back-link' do
        i.fa.fa-arrow-left.mr-2
        | К результатам выборов
      hr.mb-0

main-app/app/views/shared/_modal.html.slim
.modal[aria-hidden="true" aria-labelledby="modalLable" role="dialog" tabindex="-1" id=id class="#{'fade' unless Rails.env.test?}"]
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5#modalLable.modal-title = title
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
      .modal-body
        = yield

main-app/app/views/shared/_root_link.html.slim
.row.d-flex.justify-content-center.hp-10
  .col-sm-6.no-padding
    .col-wrapper
      = link_to root_path, class: 'back-link' do
        i.fa.fa-arrow-left.mr-2
        | На главную
      hr.mb-0

main-app/app/views/shared/_top_navbar.html.slim
nav.navbar.navbar-expand-md.bg-w.z-i-10
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation"]
    i.fa.fa-bars
  #navbarsExampleDefault.collapse.navbar-collapse
    ul.navbar-nav.d-flex.justify-content-between
      - if current_user
        - if current_user.observer?
          li.nav-item.flex-fill
            = link_to 'Профиль', profile_path, class: 'nav-link'
        - else
          li.nav-item.flex-fill
            = link_to 'Кабинет', cabinet_root_path, class: 'nav-link'
      - else
      li.nav-item.flex-fill
        = link_to 'Загрузить протокол', new_closing_protocol_path, class: 'nav-link', id: 'upload_closing_protocol'
      li.nav-item.flex-fill
        - if current_user
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          = link_to 'Войти', new_user_session_path, class: 'nav-link'

main-app/app/views/shared/_translations.html.erb
<script>
  window.I18n = <%= current_translations.to_json.html_safe %>
</script>

main-app/app/views/shared/_yandex_maps.html.erb
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=<%= Rails.application.credentials.yandex_maps_api_key %>" type="text/javascript"></script>

main-app/app/views/shared/_yandex_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(<%= Rails.application.config.yandex_metrika_id %>, "init",{clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true});</script><noscript><div><img src="https://mc.yandex.ru/watch/<%= Rails.application.config.yandex_metrika_id %>" style="position:absolute; left:-9999px;" alt=""/></div></noscript>
<!-- /Yandex.Metrika counter -->