main-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'users/:id/request_code'   => 'users/sms_verifications#request_code',   as: 'request_code'
    post 'users/:id/verify_account' => 'users/sms_verifications#verify_account', as: 'verify_account'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'
  mount ElectionObservation::Api, at: '/'

  root  to: 'home#index'
  get 'filter_stations' => 'home#filter_stations'

  resources :closing_protocols do
    get :candidates, on: :collection
  end

  resources :stations, only: %i[index show]

  namespace :results do
    resources :elections, only: %i[index show], controller: 'elections' do
      resources :districts, only: %i[index show], controller: 'elections/districts' do
        get :local_areas, on: :member

        resources :stations, controller: 'elections/stations'
      end
    end
  end

  scope module: 'users' do
    resource :profile
    resources :observers_stations, only: %i[create update destroy] do
      delete :delete_certificate, on: :member
    end
  end

  namespace :admins do
    root 'dashboard#index'

    resources :election_groups do
      patch :publish, on: :member

      resources :public_organizations, only: %i[index update], controller: 'election_groups/public_organizations'
    end
    resources :public_organizations do
      resources :users, controller: 'public_organizations/users'
    end
    resources :elections, only: %i[index create update destroy show] do
      resources :candidates, controller: 'elections/candidates'
      resources :electoral_districts, only: %i[index destroy], controller: 'elections/electoral_districts'
      resources :stations, only: %i[index update destroy], controller: 'elections/stations' do
        get :filtered, on: :collection
      end
    end
    resources :local_areas, only: :update
  end

  namespace :cabinet do
    root 'dashboard#index'

    devise_scope :user do
      get 'sign_in' => 'sessions#new'
    end

    resources :closing_protocols do
      collection do
        get :filter
        get :search
        get :reset_filter
        patch :batch_delete
      end
      member do
        patch :approve
        patch :reject
        patch :delete
        patch :batch_reject
      end
    end
    resources :users
    resources :election_groups do
      resources :observers_stations, only: %i[index show], controller: 'election_groups/observers_stations' do
        member do
          patch :approve
          patch :reject
        end
      end
    end
  end

  namespace :api do
    namespace :v1, default: { format: :json } do
      resources :regions
      resources :local_areas
      resources :stations
      resources :elections
      resources :candidates

      namespace :mobile do
        post 'user_token' => 'user_token#create'
        get 'token_login' => 'users#me'
      end
    end
  end
end

main-app/app/views/shared/admins/_box.html.slim
.ibox.float-e-margins
  .ibox-title
    h5 = title
  .ibox-content
    = yield

main-app/app/views/shared/admins/_election_nav.html.slim
.election-nav
  #election-options.nav.nav-tabs.btn-group.btn-group-toggle
    = link_to 'Общее', admins_election_path(election), class: "nav-link #{'active' if active_controller?('admins/elections')}"
    = link_to 'Избирательные округи', admins_election_electoral_districts_path(election), class: "nav-link #{'active' if active_controller?('admins/elections/electoral_districts')}"
    = link_to 'Кандидаты', admins_election_candidates_path(election), class: "nav-link #{'active' if active_controller?('admins/elections/candidates')}"
    = link_to 'УИК', admins_election_stations_path(election), class: "nav-link #{'active' if active_controller?('admins/elections/stations')}"

main-app/app/views/shared/admins/_footer.html.slim
.footer
  .pull-right
    | 10GB of
    strong 250GB
    | Free.
  div
    strong Copyright
    | Example Company © 2014-2017

main-app/app/views/shared/admins/_navbar.html.slim
nav.navbar-default.navbar-static-side role="navigation"
  .sidebar-collapse
    ul#side-menu.nav.metismenu
      li.nav-header
        .dropdown.profile-element
          a.dropdown-toggle data-toggle="dropdown" href="#"
            span.clear
              span.block.m-t-xs
                strong.font-bold Open Elections
              span.text-muted.text-xs.block
                | Admin
        .logo-element
          | IN+
      li[class=active_controller?('admins/dashboard')]
        = link_to admins_root_path do
          i.fa.fa-th-large
          span.nav-label Dashboard
      li [class=active_controller?('admins/election_groups')]
        = link_to admins_election_groups_path do
          i.fa.fa-list
          span.nav-label = t('admin.pages.election_groups.index.title')
      li[class=active_controller?('admins/elections')]
        = link_to admins_elections_path do
          i.fa.fa-user
          span.nav-label = t('admin.pages.elections.index.title')
      li[class="#{active_controller?('admins/public_organizations') || active_controller?('admins/public_organizations/users')}"]
        = link_to admins_public_organizations_path do
          i.fa.fa-sitemap
          span.nav-label = t('admin.pages.public_organizations.index.title')

main-app/app/views/shared/admins/_topnav.html.slim
.row.border-bottom
  nav.navbar.navbar-static-top.white-bg role="navigation" style=("margin-bottom: 0")
    .navbar-header
      a.navbar-minimalize.minimalize-styl-2.btn.btn-primary href="#"
        i.fa.fa-bars
      form.navbar-form-custom action="#" method="post" role="search"
        .form-group
          input#top-search.form-control name="top-search" placeholder=("Search for something...") type="text" /
    ul.nav.navbar-top-links.navbar-right
      li
        = link_to destroy_admin_session_path, method: :delete do
          i.fa.fa-sign-out
          | Log out